MinGW: Fix compilation error
Compiling ccnet on Windows using MinGW 4.8.1 will fail with the
following error:

In file included from rsa.c:11:0:
rsa.h:28:27: error: unknown type name 'u_int'

Since generate_private_key() is a wrapper around the RSA_generate_key
function and RSA_generate_key expects an int as the first argument, it
is safe to change u_int to int. This should be portable as well.