fix shared build of libccnet on mingw64
libtool complains that newer mingw64 environment don't have a real library
-lpthread, so it doesn't create a shared library while it deals with
-no-undefined

TL'DR: the de facto way of building pthread program is passing -pthread, but old
mingw gcc compiler doesn't support it. the patch addes some workarounds for both
situations.

more details:

        *** The inter-library dependencies that have been dropped here will be
        *** automatically added whenever a program is linked with this library
        *** or is declared to -dlopen it.

        *** Since this library must not contain undefined symbols,
        *** because either the platform does not support them or
        *** it was explicitly requested with -no-undefined,
        *** libtool will only create a static version of it.

more information:

        undefined reference to pthread_create in Linux
        https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux?answertab=votes#tab-top

        -pthread : Adds support for multithreading with the pthreads library. This option sets flags for both the preprocessor and linker.
        http://linux.die.net/man/1/gcc

        POSIX Threads Programming
        https://computing.llnl.gov/tutorials/pthreads/#Compiling